# from: https://github.com/mit-racecar/racecar/blob/87d6cec4ebda602dfcf39de36e7111d689859be6/racecar/config/racecar-v2/joy_teleop.yaml

joy_node:
  deadzone: 0.01
  autorepeat_rate: 20
  coalesce_interval: 0.01

teleop:
  # Default mode - Stop for safety, Sagar - seemed to cause conflicting values, need to look into it



  # Enable Human control by holding Left Bumper
  human_control_current:
    type: topic
    message_type: std_msgs/Float64
    topic_name: /commands/motor/current
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: data
        scale: -5.0                   # joystick will command plus or minus 3 amps
        offset: 0.0

  human_control_steering:
    type: topic
    message_type: std_msgs/Float64
    topic_name: /commands/servo/position
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 3
        target: data
        scale: -0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.5

  # Enable autonomous control by pressing right bumper
  # This switch causes the joy_teleop to stop sending messages to input/teleop
  # And send messages to /dev/null (an unused ROS topic)
  autonomous_control:
    type: topic
    message_type: std_msgs/Int8
    topic_name: /dev/null
    deadman_buttons: [5]
    message_value:
      -
        target: data
        value: 0
