std_msgs/Header header

std_msgs/Duration time_up
float64 dt_speed_scale

float64 control_ang
float64 steer_ang_deg
float64 steer_speed_scale

string sign
float64 light_speed_scale

float64 dist_front_left
float64 dist_front_right
float64 dist_left
float64 dist_right

float64 lidar_front_speed_scale
float64 lidar_left_speed_scale
float64 lidar_right_speed_scale
float64 lidar_speed_scale

float64 speed