
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
stoplight_controller:
  joint: light_joint
  type: position_controllers/JointPositionController
  # Will trigger an error that pid parameters are not found
  #   this leads to the intended operation mode
