lidar_noise: 0.0

chassis_length: 0.4
chassis_width: 0.13
chassis_height: 0.05

wheel_y_offset: 0.115
wheel_z_offset: 0.0098
front_wheel_x_offset: 0.1755
rear_wheel_x_offset: -0.1845

chassis_mass: 3
chassis_Ixx: 3
chassis_Ixy: 0
chassis_Ixz: 0
chassis_Iyy: 3
chassis_Iyz: 0
chassis_Izz: 3

motor_effort_limit: 0.9730
drivetrain_radius_a: 0.01605
drivetrain_radius_b: 0.0413
car_velocity_limit: 15

wheel_radius: 0.06
wheel_mass: 1
wheel_Ixx: 10
wheel_Ixy: 0
wheel_Ixy: 0
wheel_Iyy: 1
wheel_Iyz: 0
wheel_Izz: 1

wheel_gaz_mu1: 10.0
wheel_gaz_mu2: 10.0
wheel_gaz_kp: 10000000.0
wheel_gaz_kd: 5.0