<?xml version="1.0"?>
<robot name="stoplight" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:arg name="light_ns" default="sign0"/>
<xacro:property name="light_ns" value="$(arg light_ns)"/>

<xacro:arg name="scale" default="1.0"/>
<xacro:property name="scale" value="$(arg scale)"/>

<xacro:property name="pole_height" value="${0.5*scale}" />
<xacro:property name="sign_radius" value="${0.2*scale}" />

<link name="world" />
<joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
</joint>

<link name="base_link">
    <visual>
        <origin xyz="0 0 ${pole_height/2.0}" rpy="0 0 0" />
        <geometry>
            <cylinder radius="0.01" length="${pole_height}"/>
        </geometry>
        <material name="Black">
            <color rgba="1 0.0 1 1.0"/>
        </material>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10000"/>
      <inertia
        ixx="10000.0" ixy="0.0" ixz="0.0"
        iyy="10000.0" iyz="0.0"
        izz="10000.0"/>
    </inertial>
</link>

<joint name="light_joint" type="revolute">
    <origin xyz="0 0 ${pole_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="light_link"/>
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100" lower="-6.3" upper="3.3"/>
</joint>

<transmission name="light_joint_transmission" type="SimpleTransmission">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="light_joint">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </joint>
  <actuator name="light_joint_motor">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<link name="light_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
</link>

<joint name="red_light_joint" type="fixed">
    <origin xyz="0.01 0 0" rpy="0 1.5707 0"/>
    <parent link="light_link"/>
    <child link="red_light_link"/>
</joint>

<link name="red_light_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder radius="${sign_radius}" length="0.001"/>
        </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
</link>

<joint name="green_light_joint" type="fixed">
    <origin xyz="-0.01 0 0" rpy="0 1.5707 0"/>
    <parent link="light_link"/>
    <child link="green_light_link"/>
</joint>

<link name="green_light_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder radius="${sign_radius}" length="0.001"/>
        </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
</link>


<gazebo reference="base_link">
    <material>Gazebo/Black</material>
    <static>true</static>
</gazebo>

<gazebo reference="red_light_link">
    <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="green_light_link">
    <material>Gazebo/Green</material>
</gazebo>

<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>${light_ns}</robotNamespace>
    <legacyModeNS>false</legacyModeNS>
  </plugin>
</gazebo>



</robot>