racecar:
  internal:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    right_front_controller:
      type: effort_controllers/JointVelocityController
      joint: right_front_wheel_joint
      pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

    left_front_controller:
      type: effort_controllers/JointVelocityController
      joint: left_front_wheel_joint
      pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

    right_rear_controller:
      type: effort_controllers/JointVelocityController
      joint: right_rear_wheel_joint
      pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

    left_rear_controller:
      type: effort_controllers/JointVelocityController
      joint: left_rear_wheel_joint
      pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}

    # Position Controllers ---------------------------------------
    steering_controller:
      joint: front_steer_joint
      type: effort_controllers/JointPositionController
      pid: {p: 500.0, i: 0.0, d: 100}
